### PR TITLE
Embed image in show template

### PR DESCRIPTION
**Pull request by Netznarkose**

### CODE REVIEW

**Comment by eikes** [comment]
it seems like there is a lot more than just the template thingy in this PR, can you clean that up?

**Comment by Netznarkose** [comment]
I could not come up with a better solution to compare the diff between PR's then this:

https://github.com/eikes/web_charts/compare/provide_defaults_in_form...embed_image_in_show_template
https://github.com/eikes/web_charts/compare/embed_image_in_show_template...elaborate_nav_bar

I'm happy about suggestions how to organize Pull Requests in a better way upfront.

**Comment by eikes** [comment]
Whenever you work on a new feature you first need to go back to the master branch and fork it from there. If you keep forking from the branch you last worked on, you'll get pull requests like this, where everything is mashed together.

I would prefer it if you were to close this pull request, create a new branch from master and only ```git cherry-pick``` the commits which are relevant to this feature. The same goes for the other pull requests.

Can you do that?

**Comment by Netznarkose** [comment]
Yes, I get your point and I will set it up again! Just out of  curiosity: What if I want to submit several Pull Requests which depend on the changes of each other?

**Comment by kotp** [comment]
Several commits, rather than a set of PR's.  Each commit should make a change that can be supportive of the new feature, but address one aspect of it.  Doing this with PR's that hold that role means a lot more coordinated work.

**Pull request closed without merging**
